version: '3.8'

services:
  tgh_mirror:
    build: .
    container_name: tgh_mirror
    volumes:
      - ./downloads:/app/downloads
    network_mode: "host"
    restart: on-failure
    environment:
      - TZ=America/New_York
