#!/bin/bash

# Update and upgrade system packages
update_system() {
    apt-get update && apt-get upgrade -y
}

# Install Python 3.12 and essential dependencies
install_python() {
    apt-get install -y software-properties-common
    add-apt-repository -y ppa:deadsnakes/ppa
    apt-get update
    apt-get install -y python3.12 python3.12-dev python3.12-venv python3-pip libpython3.12 libpython3.12-dev
}

# Install additional system dependencies
install_dependencies() {
aioaria2==1.3.6
aiofiles==24.1.0
aiohappyeyeballs==2.6.1
aiohttp==3.11.14
aioqbt==1.0.0
aioshutil==1.5
aiosignal==1.3.2
annotated-types==0.7.0
anyio==4.9.0
anytree==2.12.1
apscheduler==3.11.0
asyncio==3.4.3
attrs==25.3.0
brotli==1.1.0
cachetools==5.5.2
certifi==2025.1.31
cffi==1.17.1
charset-normalizer==3.4.1
cinemagoer==2023.5.1
click==8.1.8
cloudscraper==1.2.71
curl-cffi==0.10.0
dnspython==2.7.0
fastapi==0.115.12
feedparser==6.0.11
frozenlist==1.5.0
google-api-core==2.24.2
google-api-python-client==2.165.0
google-auth==2.38.0
google-auth-httplib2==0.2.0
google-auth-oauthlib==1.2.1
googleapis-common-protos==1.69.2
greenlet==3.1.1
gunicorn==23.0.0
h11==0.14.0
httpcore==1.0.7
httplib2==0.22.0
httpx==0.28.1
idna==3.10
jinja2==3.1.6
langcodes==3.5.0
language-data==1.3.0
lxml==5.3.1
marisa-trie==1.2.1
markupsafe==3.0.2
motor==3.2.0
multidict==6.2.0
mutagen==1.47.0
natsort==8.4.0
oauthlib==3.2.2
packaging==24.2
par2cmdline-turbo==1.2.0
pillow==11.1.0
propcache==0.3.0
proto-plus==1.26.1
protobuf==6.30.1
psutil==7.0.0
pyaes==1.6.1
pyasn1==0.6.1
pyasn1-modules==0.4.1
pycountry==24.6.1
pycparser==2.22
pycryptodomex==3.22.0
pydantic==2.10.6
pydantic-core==2.27.2
pymediainfo==6.0.1
pymongo==4.4.1
pyparsing==3.2.3
pyrofork==2.2.11
pysocks==1.7.1
python-magic==0.4.27
pytz==2025.2
qbittorrent-api==2025.2.0
requests==2.32.3
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
rsa==4.9
setuptools==78.0.2
sgmllib3k==1.0.0
six==1.17.0
sniffio==1.3.1
speedtest-cli==2.1.3
sqlalchemy==2.0.39
starlette==0.46.1
telegraph==2.2.0
tenacity==9.0.0
tgcrypto==1.2.5
typing-extensions==4.12.2
tzlocal==5.3.1
uritemplate==4.1.1
urllib3==2.3.0
uvicorn==0.34.0
uvloop==0.21.0
websockets==15.0.1
xattr==1.1.4
yarl==1.18.3
yt-dlp==2025.3.25
}

# Main script execution
main() {
    update_system
    install_python
    install_dependencies
    install_requirements
    cleanup
}

main
